### ISSUE TITLE
Error on "Manage exercises"

### ISSUE THREAD

**Issue by rayanayar** [jl2035/moodle_mod_mootyper#10]
Pressing "To manage exercises and categories click here" leads to error:

    Debug info: ERROR: argument of AND must be type boolean, not type integer
    LINE 4: (visible = 1 AND 0) OR
    ^
    SELECT id, lessonname
    FROM mdl_mootyper_lessons
    WHERE ((visible = 2 AND authorid = 2) OR
    (visible = 1 AND 0) OR
    (1))
    ORDER BY id
    [array (
    )]
    Error code: dmlreadexception

Stack trace:

    line 443 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
    line 764 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    line 122 of /mod/mootyper/locallib.php: call to pgsql_native_moodle_database->get_records_sql()
    line 75 of /mod/mootyper/exercises.php: call to get_mootyperlessons()

May be this is because of using postgres? (instead of mysql by default)
Issue fix:

```
diff -ur ./mootyper.orig/locallib.php ./mootyper/locallib.php
--- ./mootyper.orig/locallib.php        2014-10-23 23:00:58.000000000 +0600
+++ ./mootyper/locallib.php     2014-11-11 11:28:50.700307039 +0500
@@ -109,8 +109,8 @@
     $sql = "SELECT id, lessonname
               FROM ".$CFG->prefix."mootyper_lessons
               WHERE ((visible = 2 AND authorid = ".$u.") OR
-                    (visible = 1 AND ".is_user_enrolled($u, $c).") OR
-                    (".can_view_edit_all($u, $c)."))
+                    (visible = 1 AND ".is_user_enrolled($u, $c)." = 1) OR
+                    (".can_view_edit_all($u, $c)." = 1))
               ORDER BY id";
        /*
        /// This was taken out, because we have some context_module::instance confusion
```

**Comment by drachels** [comment]
Transferred to new location.
https://github.com/drachels/moodle-mod_mootyper/issues/2
