### ISSUE TITLE
Seconds in column "Time"

### ISSUE THREAD

**Issue by rayanayar** [jl2035/moodle_mod_mootyper#16]
Suggestion.
Vaules in column "Time" contains "s" (seconds).

First. This is not translated to other languages.

Second. It is not comfortable. When exporting to CSV, this letter has to be removed each time. If need specify that the time is in seconds, then it can be done in header of column:
https://github.com/jl2035/moodle_mod_mootyper/blob/master/lang/en/mootyper.php#L63
For examle:
```
$string['timeinseconds'] = 'Time (s)';
```
As result, this string can be localized by translators. And letter "s" will not interfere in CSV table.

**Comment by drachels** [comment]
I have worked out the fix for this on my 2.7 dev site for both gview.php and owngrades.php and think that it is a logical change. I am not going to implement it just yet as I want to explore possibly showing the time in hh:mm:ss format.

**Comment by drachels** [comment]
Showing time in hh:mm:ss format was much easier to do than I thought. THis is what it looks like. I haven't implemented it here yet.
![elapsedtimeteacherviewallgradeswithelapsedtime](https://cloud.githubusercontent.com/assets/1018249/13750642/63002d42-e9d4-11e5-9bc1-b5e864d98c78.png)
![elapsedtimestudentviewmygradeswithelapsedtime](https://cloud.githubusercontent.com/assets/1018249/13750646/662be402-e9d4-11e5-8923-117c155293a8.png)

**Comment by drachels** [comment]
Switched to format_time for timeinseconds so that instead of Time it now displays as Elapsed time.
