### ISSUE TITLE
Float values are not localized

### ISSUE THREAD

**Issue by rayanayar** [jl2035/moodle_mod_mootyper#17]
Float values in Lesson/Exam mode and in grades tables are not localized. This values always shown with "." (point) decimal mark, regardless of the choosen language. But in many countries decimal mark is "," (comma):
https://en.wikipedia.org/wiki/Decimal_mark#Hindu.E2.80.93Arabic_numeral_system

Especially this is uncomfortable when exporting to CSV. LO Calc importing this CSV does not detect this values as numbers, this values are detected as text.

Moodle has special functions to display different types in user's locale. There is function "format_float" for float values:
```
... format_float($gr->hitsperminute,2).'</td><td>'.$gr->fullhits.'</td><td>'.format_float($gr->precisionfield,2) ...
```
Using this function, float values are shown with correct decimal mark, depending on choosen language in Moodle.

**Comment by drachels** [comment]
Changed to format_float for decimal numbers in csvexport.php, gview.php, and owngrades.php so they display correctly for the language in use.
