### ISSUE TITLE
Privileges violation

### ISSUE THREAD

**Issue by rayanayar** [jl2035/moodle_mod_mootyper#19]
Reproduce:
- login as student (has not teacher rights)
- go to MooTyper activity
- student have no link to "View all grades", but...
- click "View my grades" (this opens url: http://SITE/mod/mootyper/owngrades.php?id=1&n=1)
- replacing in address bar "owngrades" to "gview" will open page with all grades
- in addition, it this table student can click "Remove" and delete results of other students

In total, at least three php modules has no user rights check: owngrades, gview, attrem.

**Comment by drachels** [comment]
The fix for gview still allows people other than admin and teachers to see the Export to .csv option and it works. I have come up with a fix and will post it next time I'm online. Gotta go help my wife with something for a while.

**Comment by drachels** [comment]
Added fix for gview.php to master branch.

**Comment by drachels** [comment]
Have a working fix for owngrades.php. Will post it later.

**Comment by drachels** [comment]
Added fix to owngrades.php.

**Comment by drachels** [comment]
Transferred to new location.
https://github.com/drachels/moodle-mod_mootyper/issues/5
