### ISSUE TITLE
Backspace deletes typed text

### ISSUE THREAD

**Issue by rayanayar** [jl2035/moodle_mod_mootyper#20]
During exercise, pressing backspace deletes typed text. This does not affect to exercise results, this is "cosmetic" bug.

**Comment by drachels** [comment]
I was playing around with a very short exercises and and only two of them in a lesson and notice the itd appears that if you hit backspace enough, you can "erase" everything you've typed and will get to do the exercise over. However, the "bad" results of the erased exercise do get posted to the grades.

**Comment by jl2035** [comment]
I don't really remember why the backspace feature was added. It kinda
doesn't make sense.

**Comment by drachels** [comment]
I've been trying to figure out a way to just totally ignore the backspace key when anyone has the view page open, but no luck so far. 
I also want to try to fix issue #14 Expand tree before trying to put out a version for Moodle 2.7.13 since it was released today.

**Comment by drachels** [comment]
Transferred location.
https://github.com/drachels/moodle-mod_mootyper/issues/6
