### ISSUE TITLE
Broken grades table in Chrome

### ISSUE THREAD

**Issue by rayanayar** [jl2035/moodle_mod_mootyper#21]
Client OS: Ubuntu 12.04
Browser: Google Chrome 38.0.2125.111

![ChromeGradesTable](https://cloud.githubusercontent.com/assets/3883274/5057717/e990582e-6cf2-11e4-982d-accc82f3f6a6.png)

In FireFox this table is shown normal. Bug only in Chrome.

**Comment by drachels** [comment]
I have a fix for this and I am willing to take over maintaining MooTyper.

**Comment by yerb** [comment]
Hi,

I am the original creator of the plugin concept, and I am very happy that someone finally stepped forward with the will and time to maintain the project.

**Comment by drachels** [comment]
Added the two missing table cells in owngrades.php line 117. Checked and table displays correctly in IE, Chrome, Firefox, Safari, Opera, and MS Edge. The same problem of three missing table cells is in gview.php in line 117 and line 221. Fixed them also.
