### ISSUE TITLE
Portuguese Laytout

### ISSUE THREAD

**Issue by italoenio** [jl2035/moodle_mod_mootyper#23]
Hi,

Thanks for your work.
I did the translation into /lang/es/mootyper.php just for the strings. 
Then I changed portuguese.php inside layour folder following the instructions but I am still fighting with portuguese.js

I copied the english.js as a base and tried to add letters but I have some problems with Portuguese keyboard signs and letter  ç ;  á é í ó ú ã ão 

So I need some extra help. Where can I find some extra information? Could you help me?

Thanks for your time

**Comment by jl2035** [comment]
Sorry... I never got notification for this issue. I guess your problem is solved by now..?

**Comment by drachels** [comment]
Transferred location.
https://github.com/drachels/moodle-mod_mootyper/issues/7
