### ISSUE TITLE
erem.php needs to log exercise and category removal

### ISSUE THREAD

**Issue by drachels** [jl2035/moodle_mod_mootyper#32]
The module erem.php does not log any events at the present. It would be nice to know who did it if any exercises or categories are removed.

**Comment by jl2035** [comment]
Yes, I think this should be added. I also think the backspace feature should be removed as we discussed in #20 

Well, you are the boss now.. do as you feel. And if I didn't express this before, thanks for your dedication. It's nice to see this repo alive again :)

**Comment by jl2035** [comment]
Also you should update the plugin description at https://moodle.org/plugins/mod_mootyper

For some reason I don't have the edit link.

**Comment by drachels** [comment]
Since I haven't really looked at it yet, do you know what needs to be done to remove the backspace feature? Right now my priority is to finish adding events for logging so I can release a 2.7 versions. I think I have at least three more to do, maybe more as I learn how the different modules link together and interact.

**Comment by drachels** [comment]
Added event and trigger for removing exercises and or categories.
