### ISSUE TITLE
Error reading database

### ISSUE THREAD

**Issue by daemonsdontrest** [jl2035/moodle_mod_mootyper#34]
I have installed Mootyper for the first time and somehow got this error after clicking setup. Is this a bug? I can't configure anything since this error is persistent. 

![screen shot 2017-01-20 at 3 29 57 pm](https://cloud.githubusercontent.com/assets/25241501/22140125/6d7c7b58-df25-11e6-97a9-4ffa1615aab8.png)

Moodle version: 3.1.1 (Build: 20160711)
MooTyper version: 3.1.3 (Build: 2016101101)

##################################################################
Debug info: ERROR: argument of OR must be type boolean, not type integer
LINE 6: (1))
^
SELECT id, lessonname
FROM mdl_mootyper_lessons
WHERE ((visible = 2 AND authorid = 2) OR
(visible = 1 AND editable <= 2 AND courseid = 48) OR
(visible = 0) OR
(1))
ORDER BY id
[array (
)]
Error code: dmlreadexception
×Stack trace:
line 474 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 244 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 794 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 134 of /mod/mootyper/locallib.php: call to pgsql_native_moodle_database->get_records_sql()
line 125 of /mod/mootyper/mod_setup.php: call to get_mootyperlessons()

#######################################################################

**Comment by jl2035** [comment]
Sir, this is the wrong repo. Official code is now maintained by @drachels here: https://github.com/drachels/moodle-mod_mootyper/

**Comment by daemonsdontrest** [comment]
Hi jl2035,

Sorry for posting! I just followed the link on the official mootyper forum. It must be outdated.
