### ISSUE TITLE
Spanish Layout

### ISSUE THREAD

**Issue by nachoan** [jl2035/moodle_mod_mootyper#7]
Hi,

Thanks for your work.
I did the translation into /lang/es/mootyper.php just for the strings. 
Then I changed spanish.php inside layour folder following the instructions but I am still fighting with spanish.js 

I copied the german.js as a base and tried to add letters but I have some problems with Spanish keyboard signs and letter º ª ¿ñ  Ñ á é í ó ú

So I need some extra help. Where can I find some extra information? Could you help me?

Thanks for your time

**Comment by drachels** [comment]
Transferring to new location.
https://github.com/drachels/moodle-mod_mootyper/issues/3
