### ISSUE TITLE
Statistics are not updated when exercise ends

### ISSUE THREAD

**Issue by rayanayar** [jl2035/moodle_mod_mootyper#8]
When exercise ends, results shown on the right side are stuck. Statistics loses some last characters and last second. And this statistics differs from statistics in grades list.

Exercise ends:
![testend](https://cloud.githubusercontent.com/assets/3883274/5005397/5ad40bb2-6a4f-11e4-90c7-015dd30ab9d4.png)

Grades:
![testgrades](https://cloud.githubusercontent.com/assets/3883274/5005403/765aaecc-6a4f-11e4-8ebd-7078529c17f2.png)

P.S.
MooTyper 2.6.5 (Build: 2014102300)
Moodle 2.7.3 (Build: 20141110)
Server: Ubuntu 12.04, Apache 2.4.10, PHP 5.5.18
Client: Ubuntu 12.04, Firefox/Chrome

**Comment by drachels** [comment]
This is not an error with MooTyper. The length of the lesson being used for testing, is too short. MooTyper word length is calculated as 5 characters. If you use a minimum of 5 characters in your lesson, the lesson ends and updates as it should.
