### ISSUE TITLE
Disable exercise escape

### ISSUE THREAD

**Issue by rayanayar** [jl2035/moodle_mod_mootyper#9]
Suggestion.
Disable escape from exercise by "reload page in browser" or moving to another page. Disable only when exercise "is running" or "ended and not saved" (not pressed continue). Disable escape by browser feature "This page is asking you to confirm that you want to leave...". Same as leaving page with unsaved post in Moodle.

**Comment by drachels** [comment]
Transferred to new location.
https://github.com/drachels/moodle-mod_mootyper/issues/4
